skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resource :session, only: [:new, :create, :destroy]

  resource :users, only: [:new, :create]

  root to: redirect('/cats')
end

skeleton/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# require 'bcrypt'

class User < ApplicationRecord

    attr_reader :password

    validates :user_name, presence: true, uniqueness: true
    validates :password_digest, presence: { message: 'Password can\'t be blank'}
    validates :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6, allow_nil: true }

    after_initialize :ensure_session_token

    has_many :cats,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :Cat

    def self.find_by_credentials(user_name, password)
        user = User.find_by(user_name: user_name)
        return user if user && user.is_password?(password)

    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end
end

skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :require_logged_out, only: [:create, :new]

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to cats_url
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:user_name, :password)
    end
end

skeleton/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="user_name">Username</label>
  <input
    type="text"
    name="user[user_name]"
    id="user_name"
    value="">

  <label for="user_password">Password</label>
  <input
    type="password"
    name="user[password]"
    id="user_password"
    value="">
  <br>


  <% submit_text = (user.persisted? ? 'Update' : 'Create') + ' user!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

skeleton/app/views/users/new.html.erb
<h1>Make a new user<h1>

<%= render "form", user: @user, form_type: :new %>